version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: bizbox
      POSTGRES_USER: bizbox_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bizbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bizbox_user -d bizbox"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - coolify.managed=true
      - coolify.name=bizbox-postgres
      - coolify.type=database

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - bizbox-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - coolify.managed=true
      - coolify.name=bizbox-redis
      - coolify.type=cache

  # Database Migration
  migration:
    image: postgres:16-alpine
    environment:
      PGUSER: bizbox_user
      PGPASSWORD: ${DB_PASSWORD}
      PGHOST: postgres
      PGDATABASE: bizbox
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...' &&
        until pg_isready -h postgres -U bizbox_user -d bizbox; do sleep 2; done &&
        echo 'Running migrations...' &&
        psql -h postgres -U bizbox_user -d bizbox -c \"
          CREATE EXTENSION IF NOT EXISTS uuid_ossp;
          CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email VARCHAR(255) UNIQUE NOT NULL, name VARCHAR(255), role VARCHAR(50) DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
          CREATE TABLE IF NOT EXISTS tenants (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(255) NOT NULL, subdomain VARCHAR(100) UNIQUE NOT NULL, owner_id UUID REFERENCES users(id), settings JSONB DEFAULT '{}', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
          INSERT INTO users (email, name, role) VALUES ('admin@bizbox.local', 'Super Admin', 'super_admin') ON CONFLICT DO NOTHING;
        \" &&
        echo 'Migration completed!'
      "
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bizbox-network
    restart: "no"

  # Landing Page
  landing:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - landing_html:/usr/share/nginx/html
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Landing</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#f5f5f5;}
        .container{max-width:800px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#333;text-align:center;margin-bottom:30px;}
        .links{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin-top:30px;}
        .link{background:#007acc;color:white;padding:15px;text-decoration:none;border-radius:5px;text-align:center;}
        </style></head><body>
        <div class=\"container\">
        <h1>🚀 BizBox Multi-Tenant SaaS Platform</h1>
        <p>✅ Landing page running on port 3001</p>
        <div class=\"links\">
        <a href=\"http://194.164.89.92:3002\" class=\"link\">Admin Dashboard</a>
        <a href=\"http://194.164.89.92:3003\" class=\"link\">Website Builder</a>
        <a href=\"http://194.164.89.92:3004\" class=\"link\">Customer Portal</a>
        <a href=\"http://194.164.89.92:3005\" class=\"link\">Tenant Sites</a>
        <a href=\"http://194.164.89.92:3006\" class=\"link\">Super Admin</a>
        </div></div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  # Admin Dashboard
  admin:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Admin Dashboard</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#f8f9fa;}
        .container{max-width:1200px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#333;text-align:center;margin-bottom:30px;}
        .status{background:#d4edda;padding:20px;border-radius:5px;margin:20px 0;border:1px solid #c3e6cb;}
        .features{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px;margin-top:30px;}
        .feature{background:#f8f9fa;padding:20px;border-radius:5px;border:1px solid #dee2e6;}
        </style></head><body>
        <div class=\"container\">
        <h1>🛠️ Admin Dashboard</h1>
        <div class=\"status\">✅ Admin interface running on port 3002</div>
        <div class=\"features\">
        <div class=\"feature\"><h3>Tenant Management</h3><p>Manage customer tenants and subscriptions</p></div>
        <div class=\"feature\"><h3>User Administration</h3><p>Control user access and permissions</p></div>
        <div class=\"feature\"><h3>Analytics</h3><p>View platform usage statistics</p></div>
        <div class=\"feature\"><h3>Billing</h3><p>Handle payments and invoicing</p></div>
        </div></div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  # Website Builder
  builder:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3003:80"
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Website Builder</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#e3f2fd;}
        .container{max-width:1200px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#333;text-align:center;margin-bottom:30px;}
        .builder{background:#f1f8e9;padding:30px;border-radius:10px;margin:20px 0;border:2px dashed #81c784;}
        .tools{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin-top:20px;}
        .tool{background:#2196f3;color:white;padding:15px;border-radius:5px;text-align:center;}
        </style></head><body>
        <div class=\"container\">
        <h1>🎨 Website Builder</h1>
        <div class=\"builder\">✅ Drag-and-drop website builder running on port 3003</div>
        <div class=\"tools\">
        <div class=\"tool\">Text Editor</div>
        <div class=\"tool\">Image Gallery</div>
        <div class=\"tool\">Form Builder</div>
        <div class=\"tool\">Template Library</div>
        </div></div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  # Customer Portal
  customer:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3004:80"
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Customer Portal</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#fce4ec;}
        .container{max-width:1000px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#333;text-align:center;margin-bottom:30px;}
        .portal{background:#fff3e0;padding:30px;border-radius:10px;margin:20px 0;}
        .sections{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin-top:20px;}
        .section{background:#ff9800;color:white;padding:15px;border-radius:5px;text-align:center;}
        </style></head><body>
        <div class=\"container\">
        <h1>👤 Customer Portal</h1>
        <div class=\"portal\">✅ Customer management portal running on port 3004</div>
        <div class=\"sections\">
        <div class=\"section\">My Account</div>
        <div class=\"section\">Billing</div>
        <div class=\"section\">Support</div>
        <div class=\"section\">Settings</div>
        </div></div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  # Tenant Sites
  tenant:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3005:80"
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Tenant Sites</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#e8f5e8;}
        .container{max-width:1000px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#333;text-align:center;margin-bottom:30px;}
        .tenant{background:#c8e6c9;padding:30px;border-radius:10px;margin:20px 0;}
        </style></head><body>
        <div class=\"container\">
        <h1>🏢 Tenant Sites Renderer</h1>
        <div class=\"tenant\">✅ Multi-tenant website renderer running on port 3005</div>
        <p>This service dynamically serves tenant-specific websites based on subdomain routing.</p>
        </div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "

  # Super Admin
  super-admin:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3006:80"
    networks:
      - bizbox-network
    depends_on:
      - migration
    command: >
      sh -c "
        echo '<!DOCTYPE html>
        <html><head><title>BizBox - Super Admin</title>
        <style>body{font-family:Arial,sans-serif;margin:0;padding:40px;background:#ffebee;}
        .container{max-width:1200px;margin:0 auto;background:white;padding:40px;border-radius:10px;box-shadow:0 2px 20px rgba(0,0,0,0.1);}
        h1{color:#d32f2f;text-align:center;margin-bottom:30px;}
        .admin{background:#ffcdd2;padding:30px;border-radius:10px;margin:20px 0;border:2px solid #f44336;}
        .controls{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;margin-top:20px;}
        .control{background:#f44336;color:white;padding:15px;border-radius:5px;text-align:center;}
        </style></head><body>
        <div class=\"container\">
        <h1>⚡ Super Admin Panel</h1>
        <div class=\"admin\">✅ Super admin interface running on port 3006<br>
        Login: admin@bizbox.local | Password: ${SUPER_ADMIN_PASSWORD}</div>
        <div class=\"controls\">
        <div class=\"control\">Platform Settings</div>
        <div class=\"control\">System Monitor</div>
        <div class=\"control\">Database Admin</div>
        <div class=\"control\">User Management</div>
        </div></div></body></html>' > /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "
    environment:
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  landing_html:
    driver: local

networks:
  bizbox-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16