version: '3.8'

services:

  landing:
    build:
      context: ./apps/landing
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://194.164.89.92:3001}
    restart: unless-stopped

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://194.164.89.92:3002}
    restart: unless-stopped

  builder:
    build:
      context: ./apps/builder
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://194.164.89.92:3003}
    restart: unless-stopped

  customer:
    build:
      context: ./apps/customer
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  tenant:
    build:
      context: ./apps/tenant
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://194.164.89.92:3005}
    restart: unless-stopped

  super-admin:
    build:
      context: ./apps/super-admin
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://194.164.89.92:3006}
    restart: unless-stopped
