#!/bin/bash

# BizBox Direct Deployment Script
# Since API endpoints are different, this provides the exact deployment steps

set -e

echo "🚀 BizBox Direct Deployment Guide"
echo "=================================="

# Load environment variables
export $(grep -v '^#' .env.deployment.local | grep -v '^$' | xargs)

echo "✅ Environment loaded"
echo "🔧 Coolify URL: $COOLIFY_URL"
echo "🔑 Token: ${COOLIFY_TOKEN:0:10}..."
echo ""

echo "📋 DEPLOYMENT INSTRUCTIONS"
echo "=========================="
echo ""
echo "1. Open Coolify in your browser:"
echo "   → $COOLIFY_URL"
echo ""
echo "2. Create new project:"
echo "   → Click 'New Project'"
echo "   → Name: bizbox-saas"
echo "   → Description: BizBox Multi-Tenant SaaS Platform"
echo ""
echo "3. Add Docker Compose service:"
echo "   → Click 'New Resource' → 'Docker Compose'"
echo "   → Upload file: .coolify.production.yml"
echo ""
echo "4. Set these environment variables in Coolify:"
echo "   ============================================="
echo "   DB_PASSWORD=$POSTGRES_PASSWORD"
echo "   REDIS_PASSWORD=$REDIS_PASSWORD" 
echo "   NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
echo "   SUPER_ADMIN_PASSWORD=$SUPER_ADMIN_PASSWORD"
echo "   ADMIN_EMAIL=$SUPER_ADMIN_EMAIL"
echo ""
echo "   Optional Stripe variables:"
echo "   STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY"
echo "   STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET"
echo ""
echo "5. Deploy:"
echo "   → Click 'Deploy'"
echo "   → Monitor deployment progress"
echo "   → Wait for all services to be healthy"
echo ""
echo "6. Verify ports are open on your VPS:"
echo "   → Port 3001 (Landing Page)"
echo "   → Port 3002 (Admin Dashboard)"
echo "   → Port 3003 (Website Builder)"
echo "   → Port 3004 (Customer Portal)"
echo "   → Port 3005 (Tenant Sites)"
echo "   → Port 3006 (Super Admin)"
echo ""
echo "🌐 YOUR APPLICATION URLS (after deployment):"
echo "=============================================="
echo "Landing Page:     http://194.164.89.92:3001"
echo "Admin Dashboard:  http://194.164.89.92:3002"
echo "Website Builder:  http://194.164.89.92:3003"
echo "Customer Portal:  http://194.164.89.92:3004"
echo "Tenant Sites:     http://194.164.89.92:3005"
echo "Super Admin:      http://194.164.89.92:3006"
echo ""
echo "🔐 SUPER ADMIN LOGIN:"
echo "===================="
echo "Email: $SUPER_ADMIN_EMAIL"
echo "Password: $SUPER_ADMIN_PASSWORD"
echo ""
echo "✅ All deployment files are ready!"
echo "🎯 Follow the steps above to deploy your platform."