# BizBox Platform - Development Environment
# Optimized for local development with hot reload and debugging

version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bizbox_dev
      POSTGRES_USER: bizbox
      POSTGRES_PASSWORD: bizbox_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/core/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bizbox -d bizbox_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =============================================================================
  # FULL DEVELOPMENT ENVIRONMENT WITH ALL APPS
  # =============================================================================
  bizbox-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Landing
      - "3001:3001"  # Admin  
      - "3002:3002"  # Builder
      - "3003:3003"  # Customer
      - "3004:3004"  # Tenant
      - "3005:3005"  # Super Admin
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=development-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Source code for hot reload
      - .:/app
      # Preserve node_modules and build artifacts
      - /app/node_modules
      - /app/.turbo
      - /app/.next
      # Preserve individual app node_modules
      - /app/apps/landing/node_modules
      - /app/apps/admin/node_modules
      - /app/apps/builder/node_modules
      - /app/apps/customer/node_modules
      - /app/apps/tenant/node_modules
      - /app/apps/super-admin/node_modules
    command: ["pnpm", "dev"]
    profiles:
      - dev

  # =============================================================================
  # INDIVIDUAL APPLICATION SERVICES FOR TARGETED DEVELOPMENT
  # =============================================================================
  
  # Landing Page Development
  landing-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-landing"]
    profiles:
      - landing

  # Admin Dashboard Development
  admin-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-admin"]
    profiles:
      - admin

  # Builder Application Development
  builder-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-builder"]
    profiles:
      - builder

  # Customer Application Development
  customer-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3003
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-customer"]
    profiles:
      - customer

  # Tenant Application Development
  tenant-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3004
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-tenant"]
    profiles:
      - tenant

  # Super Admin Development
  super-admin-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bizbox:bizbox_dev_password@postgres:5432/bizbox_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3005
      - NEXTAUTH_SECRET=development-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.turbo
    command: ["pnpm", "dev", "--filter=@bizbox/app-super-admin"]
    profiles:
      - super-admin

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: bizbox_dev_network