version: '3.8'

services:
  # Landing page and marketplace
  landing:
    build:
      context: .
      dockerfile: apps/landing/Dockerfile.prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

  # Admin dashboard
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile.prod
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

  # Page builder
  builder:
    build:
      context: .
      dockerfile: apps/builder/Dockerfile.prod
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

  # Customer portal
  customer:
    build:
      context: .
      dockerfile: apps/customer/Dockerfile.prod
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

  # Tenant dashboard
  tenant:
    build:
      context: .
      dockerfile: apps/tenant/Dockerfile.prod
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

  # Super admin panel
  super-admin:
    build:
      context: .
      dockerfile: apps/super-admin/Dockerfile.prod
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizbox-network

networks:
  bizbox-network:
    driver: bridge

volumes:
  pnpm-store:
    driver: local