# syntax=docker/dockerfile:1
FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9 --activate

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./

COPY packages ./packages
COPY apps ./apps

RUN pnpm install
RUN pnpm --filter ./apps/customer build

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3004
EXPOSE 3004
CMD ["sh","-lc","pnpm --filter ./apps/customer start -- -H 0.0.0.0 -p $PORT"]